# Column names in Excel sheets
NR_ROI_COLUMN: str = "NR ROI"
LB_NR_ROI_COLUMN: str = "LB NR ROI"
UP_NR_ROI_COLUMN: str = "UP NR ROI"
HALO_DIRECT_COLUMN: str = "HALO_direct"
HALF_LIFE_COLUMN: str = "Half life"
CHANNEL_COLUMN: str = "Channel"
SEGMENT_COLUMN: str = "Segment"
CAMPAIGN_COLUMN: str = "Campaign"
GROSS_MARGIN_COLUMN: str = "Gross Margin"
SERVICE_DATA_COLUMN: str = "Service data"
ROI_RANGE_COLUMN: str = "ROI date range"
PERIOD_COLUMN: str = "Period"
